mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('volmap.urls')),
    path('admin/', admin.site.urls),
]

volmap/urls.py
from django.urls import path

from . import views


app_name = 'volmap'
urlpatterns = [
    path('', views.index, name='index'),
    path('me/', views.me, name='me'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('<int:activity_id>/signup/', views.signup, name='signup'),
    path('route/<str:destination>', views.route, name='route'),
    path('activity/<int:activity_id>/', views.activity_detail, name='activity_detail'),
]

volmap/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Activity(models.Model):
    name = models.CharField(max_length=20)
    due = models.DateTimeField()
    brief = models.TextField(max_length=200)
    site = models.CharField(max_length=50, blank=True)
    user = models.ManyToManyField(
        User,
        through='Signup',
        through_fields=('activity', 'user'),
    )

    def __str__(self):
        s = self.name
        return s


class Signup(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    achieve = models.BooleanField(default=False)
    duty = models.CharField(max_length=20, blank=True)

    def __str__(self):
        s = self.activity.name + ': ' + str(self.user) + ' - ' + str(self.achieve)
        return s

volmap/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.utils import timezone
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
import json

from .models import Activity
from .models import Signup


# Create your views here.
def index(request):
    is_auth = request.user.is_authenticated
    future_activities = Activity.objects.filter(due__gte=timezone.now())
    past_activities = Activity.objects.filter(due__lte=timezone.now())

    paginator = Paginator(past_activities, 3)
    page = request.GET.get('page')
    page_past_activities = paginator.get_page(page)

    context = {'is_auth': is_auth, 'future_activities': future_activities, 'past_activities': page_past_activities,
               'user': request.user}
    return render(request, 'volmap/index.html', context)


def me(request):
    future_activities = request.user.activity_set.filter(due__gte=timezone.now())

    # past activities
    past_activities = request.user.activity_set.filter(due__lte=timezone.now())

    paginator = Paginator(past_activities, 3)
    page = request.GET.get('page')
    page_past_activities = paginator.get_page(page)

    context = {'is_auth': request.user.is_authenticated, 'future_activities': future_activities,
               'past_activities': page_past_activities}

    return render(request, 'volmap/me.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
        return redirect('volmap:index')


def logout_user(request):
    logout(request)
    return redirect('volmap:index')


def signup(request, activity_id):
    if not request.user.is_authenticated:
        return redirect('volmap:index')

    activity = Activity.objects.get(pk=activity_id)
    sign_up = Signup.objects.filter(user=request.user, activity=activity)
    if sign_up:
        sign_up.delete()
    else:
        Signup(user=request.user, activity=activity).save()

    return redirect('volmap:index')


def route(request, destination):
    destination_point = {'keyword': destination, 'city': '北京'}
    context = {'destination': destination_point}
    return render(request, 'volmap/route.html', context)


def activity_detail(request, activity_id):
    if not request.user.is_authenticated:
        return redirect('volmap:index')

    sign_ups = Signup.objects.filter(activity_id=activity_id)
    context = {'is_auth': request.user.is_authenticated, 'sign_ups': sign_ups}
    return render(request, 'volmap/activity_detail.html', context)

volmap/templates/volmap/activity_detail.html
{% extends 'volmap/base.html' %}
{% block me_active %}active{% endblock %}

{% block body %}

<div class="container">
    <div class="row">
        {% if sign_ups %}
        <table class="table table-bordered">
            <thead>
            <tr>
                <td>Name</td>
                <td>Achieve</td>
                <td>Duty</td>
            </tr>
            </thead>
            <tbody>

            {% for sign_up in sign_ups %}
            <tr>
                <td>{{ sign_up.user.username }}</td>
                <td>
                    {% if sign_up.achieve %}
                    <span class="glyphicon glyphicon-ok"></span>
                    {% else %}
                    Pending
                    {% endif %}
                </td>
                <td>
                    {{ sign_up.duty }}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No participants.</h4>
        {% endif %}
    </div>
</div>

{% endblock %}

volmap/templates/volmap/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Love Map{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'volmap/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'volmap/bootstrap-3.3.7-dist/css/bootstrap-theme.min.css' %}" >
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'volmap:index' %}"><span class="glyphicon glyphicon-heart-empty"></span> LoveMap</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block activity_active %}{% endblock %}">
                    <a href="{% url 'volmap:index' %}">Activities</a>
                </li>
                {% if is_auth %}
                <li class="{% block me_active %}{% endblock %}">
                    <a href="{% url 'volmap:me' %}">Me</a>
                </li>
                {% endif %}
            </ul>

            {% if is_auth %}
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'volmap:logout' %}">
                        {{ user.username }}
                        <span class="glyphicon glyphicon-off"></span>
                    </a>
                </li>
            </ul>
            {% else %}
            <form class="navbar-form navbar-right" role="form" action="{% url 'volmap:login' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" maxlength="20" name="username" type="text" placeholder="Username" >
                </div>
                <div class="form-group">
                    <input class="form-control" maxlength="20" name="password" type="password" placeholder="Password" >
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-log-in"></span></button>
                </div>

            </form>
            {% if error_message %}
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <div class="alert-danger">{{ error_message }}</div>
                </li>
            </ul>
            {% endif %}
            {% endif %}

        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

{% load static %}
<script src="{% static 'volmap/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'volmap/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

volmap/templates/volmap/index.html
{% extends 'volmap/base.html' %}
{% block activity_active %}active{% endblock %}

{% block body %}

<div class="container">
    <div class="container">
        <div class="row">
            <h4>Activities around the corner</h4>
            {% if future_activities %}
                {% for activity in future_activities %}
                <div class="well well-sm row">
                    <div class="col-sm-10">
                        <p><strong>{{ activity.name }}</strong> </p>
                        <p><strong>Due:</strong> {{ activity.due }}</p>
                        <p><strong>Brief:</strong> {{ activity.brief }}</p>
                        {% if activity.site %}
                        <a href="{% url 'volmap:route' activity.site %}">Site (Map Route Plan): {{ activity.site }}</a>
                        {% endif %}
                    </div>
                    <div class="col-sm-2">
                        <form action="{% url 'volmap:signup' activity.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="activity_id" value="{{ activity.id }}" />
                            {% if is_auth %}
                                {% if user %}
                                {% if user in activity.user.all %}
                                <button type="submit" class="btn btn-default btn-sm">
                                    Cancel
                                </button>
                                {% else %}
                                <button type="submit" class="btn btn-success btn-sm">
                                    Sign up
                                </button>
                                {% endif %}
                                {% endif %}
                            {% endif %}
                        </form>
                    </div>

                </div>
                {% endfor %}
            {% else %}
            <div class="well well-sm row"><h4>No activities.</h4></div>
            {% endif %}
        </div>
    </div>

    <div class="container">
        <div class="row">
            <h4>History</h4>
            {% if past_activities %}
            {% for activity in past_activities %}
            <div class="well well-sm row">
                <div class="col-sm-12">
                    <p><strong>{{ activity.name }}</strong></p>
                    <p><strong>Due:</strong> {{ activity.due }}</p>
                    <p><strong>Brief:</strong> {{ activity.brief }}</p>
                </div>

            </div>
            {% endfor %}
            {% else %}
            <div class="well well-sm row"><h4>No activities.</h4></div>
            {% endif %}
        </div>

        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if past_activities.has_previous %}
                <li>
                    <a href="?page={{ past_activities.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                {% for pg in past_activities.paginator.page_range %}
                <li><a href="?page={{ pg }}">{{ pg }}</a></li>
                {% endfor %}

                {% if past_activities.has_next %}
                <li>
                    <a href="?page={{ past_activities.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

volmap/templates/volmap/me.html
{% extends 'volmap/base.html' %}
{% block me_active %}active{% endblock %}

{% block body %}
<div class="container">
    <div class="container">
    <div class="row">
        <h4>Sign up</h4>
        {% if future_activities %}
        <table class="table table-bordered">
            <thead>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>Due</td>
            </tr>
            </thead>
            <tbody>
            {% for activity in future_activities %}
            <tr>
                <td>{{ activity.id }}</td>
                <td><a href="{% url 'volmap:activity_detail' activity.id %}">{{ activity.name }}</a></td>
                <td>{{ activity.due }}</td>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="well well-sm row"><h4>No activities.</h4></div>
        {% endif %}
    </div>
    </div>

    <div class="container">
        <div class="row">
            <h4>History</h4>
            {% if past_activities %}
            <table class="table table-bordered">
                <thead>
                <tr>
                    <td>Id</td>
                    <td>Name</td>
                    <td>Due</td>
                    <!--
                    <td>Participants</td>
                    -->
                </tr>
                </thead>
                <tbody>
                {% for activity in past_activities %}
                <tr>
                    <td>{{ activity.id }}</td>
                    <td><a href="{% url 'volmap:activity_detail' activity.id %}">{{ activity.name }}</a></td>
                    <td>{{ activity.due }}</td>
                    <!--
                    <td>
                        {% for user in activity.user.all %}
                        {{ user }} &nbsp;
                        {% endfor %}
                    </td>
                    -->
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
            <div class="well well-sm row"><h4>No activities.</h4></div>
            {% endif %}
        </div>

        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if past_activities.has_previous %}
                <li>
                    <a href="?page={{ past_activities.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                {% for pg in past_activities.paginator.page_range %}
                <li><a href="?page={{ pg }}">{{ pg }}</a></li>
                {% endfor %}

                {% if past_activities.has_next %}
                <li>
                    <a href="?page={{ past_activities.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

volmap/templates/volmap/route.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <title>地点关键字 + 公交路线规划</title>
    <style type="text/css">
    html,
    body,
    #container {
      width: 100%;
      height: 100%;
    }
    </style>
    <style type="text/css">
        #panel {
            position: fixed;
            background-color: white;
            max-height: 90%;
            overflow-y: auto;
            top: 10px;
            right: 10px;
            width: 280px;
        }
        #panel .amap-call {
            background-color: #009cf9;
            border-top-left-radius: 4px;
   	        border-top-right-radius: 4px;
        }
        #panel .amap-lib-transfer {
	        border-bottom-left-radius: 4px;
   	        border-bottom-right-radius: 4px;
            overflow: hidden;
        }
    </style>
    <link rel="stylesheet" href="https://a.amap.com/jsapi_demos/static/demo-center/css/demo-center.css" />
    <script src="https://a.amap.com/jsapi_demos/static/demo-center/js/demoutils.js"></script>
    <script type="text/javascript" src="https://webapi.amap.com/maps?v=1.4.10&key=38dbfac589d262c87bd3aaba70038538&plugin=AMap.Transfer"></script>
    <script type="text/javascript" src="https://cache.amap.com/lbs/static/addToolbar.js"></script>
</head>
<body>

<a href="{% url 'volmap:index' %}">Back</a>

<div id="container"></div>
<div id="panel"></div>
<script type="text/javascript">
    var map = new AMap.Map("container", {
        resizeEnable: true,
        center: [116.397428, 39.90923],
        zoom: 13 
    });
    var transOptions = {
        map: map,
        city: '北京市',
        panel: 'panel',                           
        policy: AMap.TransferPolicy.LEAST_TIME //乘车策略
    };
    //构造公交换乘类
    var transfer = new AMap.Transfer(transOptions);
    //根据起、终点名称查询公交换乘路线
    transfer.search([
        {keyword: '北京师范大学',city:'北京'},
		//{{ start | safe }}
        //第一个元素city缺省时取transOptions的city属性
        //{keyword: '望京西园4区',city:'北京'}
		{{ destination | safe }}
        //第二个元素city缺省时取transOptions的cityd属性
    ], function(status, result) {
        // result即是对应的公交路线数据信息，相关数据结构文档请参考  https://lbs.amap.com/api/javascript-api/reference/route-search#m_TransferResult
        if (status === 'complete') {
            log.success('绘制公交路线完成')
        } else {
            log.error('公交路线数据查询失败' + result)
        }
    });
</script>
</body>
</html>